### ISSUE TITLE
Error compiling firmware for bpa800_p

### ISSUE THREAD

**Issue by re4s0n4** [dieselrabbit/FeitGen2_ESPHome#1]
HI there,

Pretty new to custom light platforms. Trying to use your code here. I'm guessing ESPHome changed how they do things because I am getting some errors I don't quite understand. I'm guessing they made some breaking changes since this repo was updated 3 years ago. 

`Processing office-corner (board: esp01_1m; framework: arduino; platform: platformio/espressif8266 @ 3.2.0)
--------------------------------------------------------------------------------
HARDWARE: ESP8266 80MHz, 80KB RAM, 1MB Flash
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
Dependency Graph
|-- <ESPAsyncTCP-esphome> 1.2.3
|-- <ESPAsyncWebServer-esphome> 2.1.0
|   |-- <ESPAsyncTCP-esphome> 1.2.3
|   |-- <Hash> 1.0
|   |-- <ESP8266WiFi> 1.0
|-- <DNSServer> 1.1.1
|-- <ESP8266WiFi> 1.0
|-- <ESP8266mDNS> 1.2
|-- <noise-c> 0.1.4
|   |-- <libsodium> 1.10018.1
Compiling /data/office-corner/.pioenvs/office-corner/src/main.cpp.o
In file included from src/main.cpp:39:
src/bpa800_p.h: In member function 'virtual esphome::light::LightTraits BPA800_P::get_traits()':
src/bpa800_p.h:19:12: error: 'class esphome::light::LightTraits' has no member named 'set_supports_brightness'; did you mean 'get_supports_brightness'?
   19 |     traits.set_supports_brightness(true);
      |            ^~~~~~~~~~~~~~~~~~~~~~~
      |            get_supports_brightness
src/bpa800_p.h:20:12: error: 'class esphome::light::LightTraits' has no member named 'set_supports_rgb'; did you mean 'get_supports_rgb'?
   20 |     traits.set_supports_rgb(true);
      |            ^~~~~~~~~~~~~~~~
      |            get_supports_rgb
src/bpa800_p.h:21:12: error: 'class esphome::light::LightTraits' has no member named 'set_supports_rgb_white_value'; did you mean 'get_supports_rgb_white_value'?
   21 |     traits.set_supports_rgb_white_value(false);
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |            get_supports_rgb_white_value
src/bpa800_p.h:22:12: error: 'class esphome::light::LightTraits' has no member named 'set_supports_color_temperature'; did you mean 'get_supports_color_temperature'?
   22 |     traits.set_supports_color_temperature(true);
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |            get_supports_color_temperature
*** [/data/office-corner/.pioenvs/office-corner/src/main.cpp.o] Error 1
========================= [FAILED] Took 12.68 seconds =========================
`

I would appreciate any input you may have.  

Thanks!

**Comment by dieselrabbit** [comment]
You are correct, this platform is now quite out of date with the current ESPHome.

The good news is ESPHome now natively supports what I was trying to do here, via the `rgbct` light platform. https://www.esphome.io/components/light/rgbct.html

**Comment by re4s0n4** [comment]
Thank you for your response.
